model: google/gemini-2.5-pro-preview-03-25
api: openrouter
max_tokens: 64000
temperature: null
top_p: null
concurrent_requests: 10
read_cost: 1.25
write_cost: 10.00
human_readable_id: gemini-2.5-pro*
date: "2025-03-25"