model: microsoft/Phi-4-reasoning-plus
api: vllm
max_tokens: 30000
temperature: 0.8
top_p: 0.95
concurrent_requests: 20
read_cost: 0.07
write_cost: 0.14
human_readable_id: Phi-4-reasoning-plus
date: "2025-05-01"