instruction: "Please reason step by step, and put your final answer within \\boxed{{}}.\nThe answer is an integer between 0 and 999 inclusive."
default_temperature: 0.6
default_max_tokens: 8000
strict_parsing: false
n_problems: 15
date: "2024-02-01"
dataset_path: MathArena/aime_2023_I