model: deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
api: vllm
max_tokens: 32000
temperature: 0.6
top_p: 0.95
concurrent_requests: 1
read_cost: 0
write_cost: 0
human_readable_id: DeepSeek-R1-Distill-Qwen-32B