model: deepseek/deepseek-chat-v3-0324
api: openrouter
max_tokens: 32000
temperature: 0.6
top_p: 0.95
provider:
  allow_fallbacks: False
  order:
  - Parasail
read_cost: 1.15
write_cost: 1.2
human_readable_id: DeepSeek-V3-03-24
date: "2025-03-24"